version: '3'
services:
  uaa:
    image: toquery/example-spring-cloud-gateway-uua:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"
  resource:
    image: toquery/example-spring-cloud-gateway-resource-sso:latest
    container_name: resource
    expose:
      - "9000"
  gateway:
    image: toquery/example-spring-cloud-gateway-sso:latest
    container_name: gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - resource
      - uaa
