#redis配置地址
spring:
  profiles:
    active: dev


# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# 端口
server:
  port: 80


