#redis配置地址
spring:
  cloud:
    gateway:
      routes:
        - id: api-service-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        # 增加权重配置，有 20% 的几率会错误
        - id: service1_ok
          uri: http://localhost:8081
          predicates:
            - Path=/test
            - Weight=service1, 40
        - id: service1_ok
          uri: http://localhost:8081
          predicates:
            - Path=/test
            - Weight=service1, 40
        - id: service1_error
          uri: http://localhost:8082
          predicates:
            - Path=/test
            - Weight=service1, 20
