spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://uaa:8090/uaa/token_keys

logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
