FROM adoptopenjdk:8u212-b04-jre-hotspot-bionic
MAINTAINER toquery<toquery@qq.com>
COPY target/example-spring-cloud-gateway-resource-0.0.1-SNAPSHOT.jar /app/app.jar
CMD ["java", "-jar", "/app/app.jar"]
EXPOSE 9000
